### ISSUE TITLE
RFC: New Opentracing Site

### ISSUE THREAD

**Issue by pritianka** [opentracing/opentracing.github.io#121]
## Status

Request-for-comments about the latest iteration of the OpenTracing website demoed at the OpenTracing quarterly update call. It is available at - https://reimertz.github.io/opentracing.io/ 
I am putting an issue here because @reimertz has the code on a separate repo right now (not a fork) and will push the code soon. I wanted to give everyone more time to review since we would like to release the new site by Tuesday, Oct 11, 2016.

## Problem

The current OpenTracing website contains a lot of information but it is written in an academic paper format. It is hard to get at-a-glance value of the project and know what to do next. Furthermore, there is inadequate documentation guiding people along distributed tracing. 

### Scope
For this v1 release, we should have a homepage that conveys the legitimacy of the project. The documentation needs to guide a visitor through instrumenting a large system (application or OSS project). This is meant to be a first release and we do not expect the documentation to cover every single edge case. We plan to add more documentation and other pages in future releases. 

### Current solution 
We’ve built an aesthetically appealing version of OpenTracing. The site has a new home page and GitBooks based documentation. We’ve also added documentation that guides visitors on tracing best practices. The new docs added (already reviewed by the community) are - 

[Overview](https://reimertz.github.io/opentracing.io/documentation/pages/overview.html)

[How to instrument large systems](https://reimertz.github.io/opentracing.io/documentation/pages/instrumenting-large-systems.html)

[How to instrument a framework](https://reimertz.github.io/opentracing.io/documentation/pages/instrumenting-frameworks.html)

## Corrections in progress

Please keep in mind that we are already working on the following issues with the current iteration  - 
1. Unifying the font of Docs and GitHub dropdown is different from the rest of the site. 

2. Darkening the font for the "App dev", "Framework dev" and "Why opentracing' which is so light, it feels like it's not fully colored letters.

3. Putting "join the mailing" somewhere up top in the page as well as the footer so that people can sign up.

4. Footer - 

a. Only showing the links to the top level docs instead of all of them. Overview, Quickstart, API, Instrumentation, Concepts and terminology. We can also put in Instrumenting a framework.

b. The "Connect with OpenTracing" will have the underline like the rest of the headings.

c. Removing the "News/Events" and "FAQ" for now.

d. Putting the following under Resources and removing the rest - About, Blog, Supported Tracers

e. Putting the following under Ecosystem and removing the rest - GitHub, Mailing list, Twitter, Blog

## Proposed next steps

Please review this at your convenience. We would like to release the new site by Tuesday, October 11th. So it would be helpful to have comments in before that.

Thanks very much!

_cc @bensigelman @reimertz_

**Comment by yurishkuro** [comment]
👍 Love the new look! 

A few comments
---
The logo on the home page is quite small, it can actually be made bigger than the navigation bar, e.g. as here http://polyakovproductions.com/
---
when the home page scrolls down, the navbar traditionally stays at the top 
---
would be cool if the main blue background did not scroll, but the white background below would slide up onto it (see same site above as example).
---
the favicon is missing from both home page and the docs pages
---
what do the icons (apple, yelp, etc.) represent?
---
I think the current bash screenshot on the home page has little to do with opentracing API. I would instead show some very basic examples of instrumenting a function, in 3 tabs, for Go, Java, and Python. E.g. in Go:

```go
import (
  "github.com/opentracing/opentracing-go"
  "github.com/opentracing/opentracing-go/log"
)

func DoSomeWork(ctx context.Context, workID int) {
    span := opentracing.StartSpanFromContext(ctx, "DoSomeWork")
    defer span.Finish()
    span.SetTag("workID", workID)
    // do the work
}
```
(I wasn't sure if we want to add example of kv logging here, it's a bit heavy in Go)

Java and Python can have similar examples, with `try(span)` and `with span:` constructs for auto-finishing.
---
Concepts and Terminology page could use splitting up in the sidebar menu
---
I would rename "across process tracing". Maybe "Crossing Process Boundaries". And the page title "everything you wanted to know..." is best renamed to match the menu item.
---
Finally, I feel that using the blog post for the Quick Start page is rather heavy. If this was my first time with the API, I would be looking for examples like above on the home page as the "quick start". Those examples don't actually need to be a complete application, because they just need to introduce the concepts. The problem with showing a complete application is that it's (a) tied to a single language that not all readers may be familiar with, and (b) inevitable requires a lot more boiler plate code to make it work, which obscures the introduction of the actual API. 

Note that gRPC docs actually provide a quick start guide for each language. In case of OT the things are a bit simpler, imo, since we don't need to discuss the setup for a quick guide, just show code examples, co-mixed with paragraphs of explanations. We can auto-generate the per-language guides by inserting the code examples into a shared template.

**Comment by reimertz** [comment]
@pritianka @bensigelman 

I have created a pull-request now: https://github.com/opentracing/opentracing.github.io/pull/122
It's quite massive. You can see the result of it over at https://reimertz.github.io/opentracing.github.io 

note that that this url is different from the link @pritianka shared above.

**Comment by pritianka** [comment]
One note - the GitBooks documentation doesn't show OT logo in the tab but some other thing and the title of the doc.

**Comment by pritianka** [comment]
It would be helpful to have "Organizations using OpenTracing" above the company logos.

**Comment by fractaly** [comment]
Hi @yurishkuro, really happy to hear that:) 

Great feedback, I will answer the comments related to design below.

We can definitely make the logo bigger so it stands out a bit more, no problem.

Regarding the navbar, we actually discussed having a navbar that stays on top initially, but were thinking that the short format of the landing page makes up for having this, and that it looks neater without it in this case. Does that makes sense?

Regarding fixed backgrounds, because of the shenanigans one have to utilize to get consistent 60 fps in older browsers, this doesn't feel like a low hanging fruit at the moment. 

If you don't feel strongly about this one, I'd prefer if we could skip this for now and potentially do a new pull-request further on, adding legit fixed backgrounds utilizing window.requestAnimationFrame. 
 
Thanks for pointing out the favicon issue, we will fix this ASAP!

The icons (apple, yelp, etc.) represents companies that are currently using OpenTracing. To make this clearer we will add a small caption saying "Organizations using OpenTracing" as suggested by Priyanka.

Regarding the docs and content related comments, @pritianka and/or @bensigelman will look into this!

**Comment by pritianka** [comment]
Update on docs - I changed the title to "Crossing Process Boundaries" for the relevant doc. I also fixed some typos and moved the authors and contributors to the bottom. 

Re QuickStart - As discussed with @yurishkuro will wait till v2.

Re bash window - @bensigelman is providing some content that takes your suggestion @yurishkuro 

@reimertz - please let me know if I need to do anything else to make the docs changes propagate.

**Comment by bensigelman** [comment]
So I merged the PR just now since we're going to get a bunch of traffic soon. Here are a bunch of things that are busted:

- [ ] the OT logo is a 404 in at least one place... I think we can just remove it, though, it looks funny to me (this is in the "intro" page of the gitbook area)
- [ ] no Google Analytics anymore
- [ ] the "edit this page" links are broken; we should prob remove them for now and add back once the dust settles and we have time to fix
- [ ] a bunch of copy-editing concerns for links, etc... I can take a pass at these
- [ ] the code snippet on the landing page doesn't work
- [ ] lots of out-of-date info about tracer impls, contributors, etc -- this was true on the old site, too :)

**Comment by bensigelman** [comment]
I'm literally :zzz:, so I must stop... fixed a bunch of stuff above. Also fixed a bunch of things that weren't on the list.

Still to do:

- [ ] Google Analytics is enabled for the landing page, but not for the gitbook stuff
- [ ] "Contributors" is out of date, and would be better for it to be dynamic as has been said many times before
- [ ] Much of the doc content could be reorged or consolidated, but so it goes... not going to fix that before tomorrow morning.

**Comment by reimertz** [comment]
fixed the following now
- [x] Google Analytics is enabled for the landing page, but not for the gitbook stuff
- [ ]  "Contributors" is out of date, and would be better for it to be dynamic as has been said many times before
 - [ ] Much of the doc content could be reorged or consolidated, but so it goes... not going to fix that before tomorrow morning.
 - [x] The 404 page has broken links (recursion! :)
cc @pritianka @reimertz ^^^

**Comment by bensigelman** [comment]
I'm going to close this since the site has been live for the better part of 24h now -- thanks again, @reimertz @fractaly for all of the hard work and @pritianka for coordinating!
