### ISSUE TITLE
Should we allow multiple values for the same tag key

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/opentracing.github.io#16]
Splitting into a separate issue the discussion about `set_tag` vs. `add_tag`, started on #14 and in https://github.com/opentracing/api-python/commit/15d3009d7eb646f46e565f4487189684e5168cc6#commitcomment-15357389

@slimsag @bensigelman @adriancole

**Comment by yurishkuro** [comment]
I will have a chat with different users tomorrow to see if they have any concrete use cases for multi-valued tags. If they do not, I'd be ok to restrict the API to set_tag for now, with the explicit disclaimer that _if the user calls set_tag multiple times for the same key, the behavior of the tracer is undefined, i.e. it is implementation specific whether the tracer will retail the first value, or the last value, or pick one randomly, or even keep all of them._

**Comment by bensigelman** [comment]
All sgtm. Thank you!

On Sunday, January 10, 2016, Yuri Shkuro <notifications@github.com> wrote:

> I will have a chat with different users tomorrow to see if they have any
> concrete use cases for multi-valued tags. If they do not, I'd be ok to
> restrict the API to set_tag for now, with the explicit disclaimer that *if
> the user calls set_tag multiple times for the same key, the behavior of the
> tracer is undefined, i.e. it is implementation specific whether the tracer
> will retail the first value, or the last value, or pick one randomly, or
> even keep all of them.*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opentracing/opentracing.github.io/issues/16#issuecomment-170410793>
> .
>


-- 
Sent via mobile

**Comment by adriancole** [comment]
I'm primarily in favor of setTag vs addTag. I find the latter more expensive to support, and will lead to more complex documentation, data structures and backends. SetTag is more accessible.

### Implementation impact for addTag(String,String)
If we add this to the api, there are a few things that will happen. We will need to document and adjust tests knowing this feature won't be widely supported (ex in google cloud trace, htrace, and probably others). Representations must be more complex, as they now have to use a structure more complicated than String->String. For example, it now would need to be a List of 2 or 3 tuples depending on whether or not order is preserved. Moreover, querying and indexing will need to operate against such a structure. For example, querying for a key within json is no longer an equals comparison with an association. Rather it is a search among keys. Eventhough some systems like zipkin currently support storing this sort of structure (eg its raw span), it has led to numerous bugs and complaints. The complexity and implementation burden of zipkin is a primary reason why it is so slow moving, and so I can't in good faith advocate for something like addTags with the experience I have.

### Motivation for addTag(String,String)
In discussion, the primary use case for this feature was multiple parents, which is hard to argue as being a "tag" because parents or other trace identifier metadata is not a user-concern, rather a propagation one. If we wanted to support multiple parents, this would be an issue about trace/propagation *attribute*, not tag, which would be far less surface area and less concerning.

For example, I would be surprised if "joe developer" would be interacting with trace identifiers as often as they do tags, so supporting multiple parents should really be a trace/parent attribute discussion.

In attempts to not refine my selection bias, I've taken time to call out tracing systems that are in each (or in the case of zipkin both) camps. I've cc'd folks who seem to know background, so maybe they can contribute use cases for multiple values or why they accept only single value.

### setTag(key,value) and systems that support it 

A user's expectation of setTag(key,value) would be that by the time it comes back to the system, they receive the last association back.

ex. `setTag("foo", "bar")`, `setTag("foo", "baz")`, `setTag("foo", "bar")` would be `"foo" -> "bar"`

#### Htrace
[htrace v4](https://github.com/apache/incubator-htrace/blob/master/htrace-core4/src/main/java/org/apache/htrace/core/Span.java#L119) key value mappings are single-value cc @cmccabe

#### Cassandra
[cassandra](https://github.com/apache/cassandra/blob/trunk/src/java/org/apache/cassandra/tracing/Tracing.java#L191) trace parameters are single-value cc @michaelsembwever

#### Google Cloud Trace
[google cloud trace v1](https://cloud.google.com/trace/api/reference/rpc/google.devtools.cloudtrace.v1#google.devtools.cloudtrace.v1.TraceSpan) labels are String -> String mappings. cc @bogdandrutu

#### grpc Census Tracing
[grpc census tracing](https://github.com/grpc/grpc/blob/bbb94bd6fcb85c27498c85724340bbaaf30be6b0/include/grpc/census.h#L342) tag sets indicate a new value replaces an existing one cc @a-veitch

#### Spring Cloud Sleuth
[spring-cloud-sleuth v1](https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/Span.java#L121) annotations are String -> String mappings. cc @dsyer

#### Zipkin v1
Eventhough [Zipkin v1's Binary annotation](https://github.com/openzipkin/zipkin/blob/master/zipkin-thrift/src/main/thrift/com/twitter/zipkin/zipkinCore.thrift#L248) can store this multiple associations the query api, tests and some backends assume there's only one value per key. All instrumentation libraries I've seen log only a single value with a key per span. This has led to calls for simplification in [Zipkin v2](https://docs.google.com/document/d/1ixxEs9TvhiGjJObGbRSPhSna3zHdadoUTQIZ5JKgLzU/edit). cc @jcarres-mdsol

### addTag(key,value) and systems that support it 
A user's expectation of addTag(key,value) would be that by the time it comes back to the system, they receive all associations, and I am quite sure some will want them in order, and perhaps even deduped.

ex. `addTag("foo", "bar")`, `addTag("foo", "baz")`, `addTag("foo", "bar")` would be `"foo" -> ["bar", "baz", "bar"]` or something similar depending on what a user might think.

#### AppDash
[appdash](https://github.com/sourcegraph/appdash/blob/master/internal/wire/collector.proto#L21) annotations are not atomic. For example a log message is a combination of a key for the message and another key for the timestamp. As such, the data structure underneath must support repetition. Given that OpenTracing has a log message, it is unclear to me which use cases, if any, of appdash require addTag vs setTag in the OpenTracing api cc @slimsag 

#### AppNeta v2
[appneta](http://dev.appneta.com/docs/api-v2/annotations.html) supports add tags and its data structures include metadata including the timestamp. I don't know if users use this feature primarily for history or as a multimap cc @dankosaur

### Pinpoint
[pinpoint](https://github.com/naver/pinpoint/blob/master/commons/src/main/java/com/navercorp/pinpoint/common/bo/Span.java#L31) spans include a list of annotations which have key/value mappings. These can repeat. cc @Xylus

#### Zipkin v1
[Zipkin v1's Binary annotation](https://github.com/openzipkin/zipkin/blob/master/zipkin-thrift/src/main/thrift/com/twitter/zipkin/zipkinCore.thrift#L248) can store this multiple associations (lossy on order). See notes on setTag above about practicalities.

**Comment by adriancole** [comment]
>
> I will have a chat with different users tomorrow to see if they have any
> concrete use cases for multi-valued tags. If they do not, I'd be ok to
> restrict the API to set_tag for now, with the explicit disclaimer that *if
> the user calls set_tag multiple times for the same key, the behavior of the
> tracer is undefined, i.e. it is implementation specific whether the tracer
> will retail the first value, or the last value, or pick one randomly, or
> even keep all of them.*
>
While I'd prefer that tracers are consistent on this, I concede backends
won't be. I'm happy that we settle with set_tag, as I'd prefer the
disclaimer to be in this direction vs the other way around.

**Comment by adriancole** [comment]
There was an aside, where @yurishkuro [compares a decision here](https://github.com/opentracing/api-python/commit/15d3009d7eb646f46e565f4487189684e5168cc6#commitcomment-15362017) vs stackoverflow multiple tags.

The word "tag" is commonly associated with a single string. Ex stackoverflow expects an [array of strings](https://api.stackexchange.com/docs/types/question) in their request object. In apis like EC2, they support tag concept above, by simply providing a [key with an empty value](http://docs.aws.amazon.com/AWSEC2/latest/CommandLineReference/ApiReference-cmd-CreateTags.html).

**Comment by adriancole** [comment]
fwiw the predominant reason I've not raised objection to the word "tag" was EC2's use of the term. Since EC2 uses it, I can relate to people by saying "this is like EC2 tags, not SO tags". Otherwise, I would have objected bc when I think tag, I think a single string, not an association.

**Comment by bogdandrutu** [comment]
I would strongly encourage to use set_tag. Here are some of the reasons:
* We want to always propagate this values with the context (supporting multi-values will add complexity and overhead).
* As adriancole@ suggested tag is a single string and we explicitly picked this name because of this.
* Keeping it consistent with other implementations (like EC2 is a nice thing).
* grpc + google will be consistent with this.

Few things to remember and how I see the difference between tag and annotation (Remember Rodrigo's paper):
* Tag: String -> String
* Annotation: Timestamp -> String
* Tag is propagated with the context;
* Annotation is a one time event (it is not getting propagated).

**Comment by cmccabe** [comment]
I haven't seen a case in HTrace where we wanted multiple values for a
specific tag before (although perhaps one will come up in the future?)
 Anyway, it seems like people who want multiple values for an individual
tag can always use a comma-separated list, or some other user-defined
mechanism for doing that, given that tags are strings.

best,
Colin

**Comment by yurishkuro** [comment]
@bensigelman @adriancole I got a "No" answer from users.

@slimsag are you ok with converging on `set_tag` for now?  The disclaimer in the method will be:

> _if the user calls set_tag multiple times for the same key, the behavior of the tracer is undefined, i.e. it is implementation specific whether the tracer will retain the first value, or the last value, or pick one randomly, or even keep all of them._

If all agree I'll do a PR for api-python and publish a new release.

**Comment by bensigelman** [comment]
(Thanks for polling people at Uber, Yuri... all SGTM if @slimsag is ok with it.)

**Comment by slimsag** [comment]
SGTM

**Comment by dankosaur** [comment]
The only case where TraceView takes advantage of multiple key addition is for multiple `Edge` values (i.e. multiple parents).  We haven't found any other interesting use-cases for multiple keys.  If metadata like edges to other spans/events is handled separately, that allows for a separate discussion on multiple edges.

**Comment by adriancole** [comment]
I'm thankful for folks speaking up about this. I learned a lot.

**Comment by bensigelman** [comment]
+1 -- Dan, very helpful notes!

**Comment by yurishkuro** [comment]
Python changes have been made in https://github.com/opentracing/api-python/pull/6

Thanks to everyone who provided their perspective, it was very useful. I am going to close this.
