### ISSUE TITLE
Drop the case-insensitivity requirement on trace attributes

### ISSUE THREAD

**Issue by adriancole** [opentracing/opentracing.github.io#25]
I'd like to drop the case-insensitive requirement, ex. the 'i' part of the below reference.

> Note 3: keys are case-insensitive, to allow propagation via HTTP headers. Keys must match regex {@code (?i:[a-z0-9][-a-z0-9]*)}

To propagate through HTTP headers, we only need to be lowercase. Moreover, HTTP/2 actually requires this at the transport level. The case-insensitivity aspect of above only makes more work for implementors.

For example, `TraceContext.getAttribute` now has to do case-insensitive lookup. At least in java, there's no case-insensitive map in the standard library. That would mean we'd need to make one, only to satisfy that requirement.

Moreover, at least in zipkin, we learned that many storage systems do not support case insensitivity. For example, in Manhattan, keys are stored as byte arrays.

I'd like the easiest implementation with the least edge cases. I don't think we are being served by supporting case-insensitive trace attribute keys.

**Comment by bensigelman** [comment]
@adriancole this is not meant to be snarky / rhetorical: isn't case-insensitive `getAttribute` just a matter of lowercasing the key string that's passed in? My assumption was that implementations would just `toLowerCase` everything passed in by users, thus obviating the need for storage services to know/care about this.

Anyway, the reason I went with case-insensitivity is because Go's HTTP client library uppercases the first letter of every header as well as anything following a `-`:

  https://github.com/golang/go/blob/master/src/net/textproto/reader.go#L554

... which is annoying, but means that the keys coming off the wire – at least when Go HTTP code is involved, though I read about this and it sounds like lots of HTTP servers do stupid things – are going to be in mixed case much of the time *anyway*, so we may as well get used to lowercasing things.

**Comment by adriancole** [comment]
I'd prefer to tell users that they should lowercase things, even if we
don't not fail if they don't... verses document things are case insensitive
and relegate the reality of down-casing to tribal knowledge of implementors.

But I already said that, I suppose, by opening this issue.

**Comment by bcronin** [comment]
I'd side with Adrian and say I'd prefer "must be lowercase" over "case insensitive" -- it's subtle, but "must be lowercase" leaves little room for ambiguity. As a practical but anecdotal point, my experience has been "case insensitivity" is far more subject to defects, especially in roundtripping.

**Comment by bensigelman** [comment]
So, there are two places that attribute keys are specified as strings:

1. via `TraceContext.SetTraceAttribute` (in whatever language)
2. via `TraceContextDecoder.TraceContextFromText` (also in whatever language... and soon to be `TraceContextCodec`)

If we say the keys MUST be lowercase (or it's undefined-behavior-time), are we just talking about `SetTraceAttribute`, or also in the decoder? If the latter, when calling code grabs the attributes from HTTP headers, they will need to be fastidious about calling `ToLower` or equiv on them... I don't know, it just seems subtle and error-prone since it's sometimes hard to remember that HTTP interlopers (load-balancers, random HTTP clients, etc) meddle with header casing.

But I don't feel super strongly about this and it sort of sounds like @adriancole does? If that's the case, I'll budge :)

**Comment by bensigelman** [comment]
@yurishkuro per some informal conversations lately, is Uber comfortable with dropping the requirements on baggage keys entirely? (Well, aside from the requirement that they be valid utf8 strings)

If so, I might close this issue and replace with one to make OT and basictracer more flexible in this regard.

**Comment by yurishkuro** [comment]
I need to think about how such change can be introduced in production where lots of services are using client libraries with the current key assumptions. Specifically, our existing format of `{prefix}{user_key}` for http headers will not work once the restriction is lifted. Basic tracer also uses that mechanism and will also be affected.  Do you have thoughts on how basic tracer's propagation format will change as a result?

**Comment by bensigelman** [comment]
@yurishkuro yes, agreed that the current assumptions about http headers will not work well if we lift key restrictions.

I would argue for a single HTTP header _key_ for all baggage... since HTTP headers are a multimap, we could still decide whether to encode the K baggage items as K HTTP header pairs (all sharing a single HTTP header key) or as a single consolidated HTTP header pair. The important thing (IMO) is getting rid of the restriction on the baggage keys, as it's awkward to rationalize and awkward to enforce.

**Comment by yurishkuro** [comment]
@bensigelman I am a bit skeptical about the multi-map semantics of headers being correctly implemented in all the different http frameworks in all languages. It also rather defeats the readability purpose of the prefix-based encoding, since the rhs will be storing something like `url.encode("{key}={value}")`. 

Anyway, I am recommending to my users to stick with lower-case-dash-separated-keys, which will continue working with the existing client libraries, and we can built support for general purpose utf8 keys through other means, most likely via `{prefix2}_{seqNo}: {url.encode("{key}={value}")}`, which will preserve _some_ readability, avoid multi-map pitfalls, and play better with the max length of the header value.

Do you want to open a new issue with the corresponding title, and get +1s from more people?

**Comment by bensigelman** [comment]
Sure, will do later today or tomorrow. Anything that removes the restrictions from the actual `SetBaggageItem` API sgtm.

**Comment by bensigelman** [comment]
(If we proceed with https://github.com/opentracing/opentracing.github.io/issues/95, this issue will no longer be relevant)

**Comment by bensigelman** [comment]
This is basically equivalent to https://github.com/opentracing/opentracing.github.io/issues/95 (which looks to be moving forward).
