### ISSUE TITLE
How can a user request a trace to be sampled

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/opentracing.github.io#43]
Opening this as a placeholder for outstanding issue of force-sampled traces, aka "debug" flag.

- [x] need to have an ability to set this flag before the root span is started, since many tracers make sampling decisions upfront
- [x] need to agree on the name ("debug" or "force-sampling") and means of setting this flag

**Comment by CodingFabian** [comment]
While vendors will implement their own sampler and trace data collectors, I personally think it would be great to have the spec define a common denominator or maybe just a "hint".

Right now, Sample: yes/no is done by samplers and then passed downstream, this is done so that the trace is consistent.
A better alternative could be to use something like `trace-level`which indicates how much data a trace shall collect. 0 could be identical to sample = off, but other values like 5 could be basic trace data (spane attributes) and 10 extended trace data.

**Comment by beberlei** [comment]
We do this by sending additional HTTP headers with the request that are evaluated during the creation of the first/root span, it then decides about no tracing, "production traffic tracing" and developer tracing. But this requires the information to be available inside `createSpan()`

**Comment by dkuebric** [comment]
@CodingFabian that sounds good.  How about `tracePriorityHint` with some defined range of integer values?

@beberlei agreed this interface would need to make the information available to the tracer at the time of `createSpan` call (or equivalent).

My vote would be as extended optional parameter to `startTrace` (or equivalent)?

**Comment by bcronin** [comment]
(Quick preface: if there's a discussion on this elsewhere that I've missed, please point it out - I don't mean to cause rehashing of existing discussion!)

Is there a clear use case for why this needs to be part of the OpenTracing spec and not an implementation detail? I'm not saying there isn't -- I just would like to keep the spec as trim as possible if it can be made implementation-dependent (and still accomplish everything it needs to).  This sort of has the "feel" of a feature rather than part of the must-support spec to me.

Per the "set this flag before the root span is started" requirement, can this be done as part of the implementation-dependent initialization? That implementation specific config needs to happen somewhere, so can the flag / config option be up to the implementation to determine how to specify?

As for cross-process propagation of this configuration, I have been assuming that OpenTracing 1.0 supports only a system that using the same underlying tracing implementation in every process / service. This means that if a process configured with Tracing Implementation XYZ receives a HTTP request, it can assume Tracing Implementation XYZ (or no implementation) was being used when the HTTP request was sent -- and make implementation-specific assumptions about what is / is not going to be in the HTTP headers. In other words, how the flag is specified across processes again can be implementation dependent.

Apologies if I'm missing something obvious!

**Comment by CodingFabian** [comment]
@bcronin No you are not missing an important point. my argument is that implementations need to do that anyways, so it would be great for interop to spec it. Your argument that it is not required for the spec is of course valid.
If interop is not a concern for 1.0, my argument is less valid. But my basic assumption is that somebody willing to go through the pain of agreeing on a spec has interop in mind.

**Comment by dkuebric** [comment]
To clarify, I'm in favor of deferring this until after 1.0 as mentioned on the chat this morning.  My hope is that by having a bit of discussion about interfaces in this thread, we can provide some perspective on interop for Tracer developers concerned with this topic such that Tracers will be more amenable to reificiation in API down the road.

Agree with @bcronin about ability to rely in implementation-specific for now, though because it may be request-specific it would have to happen potentially at each entry point of tracing, not just at Tracer initialization.  (This is the type of learning we'll get from some actual implementations before OT API.)

**Comment by yurishkuro** [comment]
> That implementation specific config needs to happen somewhere, so can the flag / config option be up to the implementation to determine how to specify?

The thing is, as an application developer, I should not be exposed to any tracer implementation specific details, that's the point of OpenTracing. From what I hear it's a fairly common practice to allow developers to have a way to specify that they want a particular trace sampled regardless of the tracer's default sampling policy. If I want to switch the tracing implementation for another one, I should not be forced to rewrite the app code that deals with 'debug'  traces.

Note that we're not talking about standardizing _how_ the debug flag is specified in the request (headers or what not), that's the end application's business, but once the app decided it needs to set a debug flag, OpenTracing should have a way to do that in a vendor-neutral manner.

**Comment by beberlei** [comment]
One problem with the current API differentiating between startTrace and joinTrace* is, that every service needs to implement the code deciding between start+join and potentially debug or not (levels/priorities) and do this in a way that is secure, so that user facing services cannot be DDoSed by users requesting traces with very high level of details.

Unless you pass the information to the Tracer outside of the OpenTracing API, there is little possibility to let the vendor make all this decisions. Which removes burden from developers to possibly re-implement this over and over again. It can also make it easier to enforce

I am wondering if `startTrace(operationName, blobOfAttributes)` (similar how the python api already allows to pass tags) would allow more flexibility for the vendor to decide on things.

**Comment by yurishkuro** [comment]
> I am wondering if `startTrace(operationName, blobOfAttributes)` (similar how the python api already allows to pass tags) would allow more flexibility for the vendor to decide on things.

One thing we've said a few times is that we have another ticket #22, which requires somewhat similar extension of the API to accept externally generated timestamps, so the solution to "debug" trace might be similar to what we come up with in #22.

**Comment by yurishkuro** [comment]
@bcronin @CodingFabian the "interop", as in between different tracing systems, is a non-goal for OpenTracing. As such, this ticket is not trying to say anything at all about how the "debug" flag is propagated between processes, just like in general OpenTracing API has nothing to say about how span ID is propagated. By "how" I mean "in what form, on the wire", because OT does have vendor-neutral API to encode a span into intermediate representation (binary or text) that an RPC framework can use to include on the wire.

**Comment by bensigelman** [comment]
Would it be sufficient to decide on the canonical name of a trace annotation key which represents debug-ness? This reminds me of some of the `const` declarations we've talked about putting in an `extensions` namespace for various languages.

As for sequencing, I don't think this issue should block a 1.0 release, but I also don't mind discussing it in the meantime.

**Comment by beberlei** [comment]
@yurishkuro you are right about seperating (de)serialization of context into another object, so maybe its not `blobOfAttributes`, but `startTrace(operationName string, context map[string]string)` and then something else is responsible to create the map of context.

**Comment by yurishkuro** [comment]
@bensigelman yes, it could be sufficient provided that we have a way to set the tags ahead-of or during root span creation.

@beberlei I was thinking more like

```go
func startTrace(operationName string) Span
func startTraceWithOptions(operationName string, options *Options) Span

type Options struct {
    context map[string]string
    // other stuff, in the future
}
```

With this approach, the forced sampling can be a proper attribute in the Options struct, rather than a tag

**Comment by yurishkuro** [comment]
@bensigelman I realized that the problem may be simpler than I initially thought. I assumed that the tracer immediately needs to know that a trace is sampled, as otherwise it might already short-circuit storing certain events/tags. But in practice, when I implemented the tracer, it would work just fine as long as the "debug" flag is set immediately after creating the root span. That seems like a reasonable compromise for the end user, if you want to have everything recorded on a debug trace, you have to mark it as such asap.

Of course, if tracers choose to implement non-sampled traces with a completely different, less capable class like NoopSpan (as I think @tschottdorf was trying to), then it won't work, but that seems like the wrong approach for the tracer to take anyway, especially because no-op span cannot propagate TraceAttributes, which should be unaffected by the sampling.

**Comment by tschottdorf** [comment]
> That seems like a reasonable compromise for the end user

I agree.

> Of course, if tracers choose to implement non-sampled traces with a completely different, less capable class like NoopSpan (as I think @tschottdorf was trying to), then it won't work, but that seems like the wrong approach for the tracer to take anyway, especially because no-op span cannot propagate TraceAttributes, which should be unaffected by the sampling.

What I want to avoid is putting log events into a trace that I know I'm not interested in. I have no trouble using the same Span for such traces, but I don't want every call to `LogEvent` to accumulate data into the `Span` when I know for a fact I won't use it. That and just not yet wanting to fork `standardtracer` (anticipating its change in the face of current interface discussions) are the reasons for using a separate `NoopSpan` currently, but I do see that as a temporary crutch. It's easy enough to flag a Span such that it   ignores LogEvent calls.

**Comment by bensigelman** [comment]
@tschottdorf mainly just FYI, I think `standardtracer` is a fine idea (almost as much for documentation purposes as coding purposes) but will almost certainly move out of `opentracing-go` in the near future... ultimately it's a distraction for *callers* of OT (who are the priority, ultimately).

Also, as long as `StandardTracer` knows about sampling, it would be easy enough to have non-sampled Span instances turn everything aside from codec tasks and perhaps Trace Attribute calls into noops...

**Comment by bensigelman** [comment]
Oh, @yurishkuro, good to know. I still like the idea of supporting tags at Span construction time as a base API, but nice to know it's not a requirement for any particular use case we have today.

**Comment by bensigelman** [comment]
I'm curious whether people think that Tags (a la #50) are an acceptable way to force sampling. It would literally "work", but part of me thinks that sampling should not need to be exposed in the Tags.

**Comment by tschottdorf** [comment]
It seems slightly hacky but then upfront sampling may not make sense for
all tracer types. What's the alternative? Some Netflix
Method ShouldTrace on Span?

**Comment by adriancole** [comment]
just read through all this.. a particularly interesting thread. Where before-the-fact sampling occurs (ex in zipkin tracers), knowing sampled state (or a range like proposed here) up front indeed gives a lot of implementation flexibility. If it is set via options, then implementations don't have to deal with mutability of that state later.

On the idea in general, the only thing that makes this api affecting is that the user is contributing to the sampling decision. Ex the user requests a certain level (likely to be most detail), and the internals would choose to honor that or not.

PS Zipkin's debug flag goes all the way to the collector tier, so we should certainly note strongly this is a request, not an assertion of a level.

**Comment by yurishkuro** [comment]
With https://github.com/opentracing/opentracing-go/pull/50 the first checkbox is done.

For the naming, @bensigelman proposed this on gitter:

> my two cents: the portable way to describe this is in terms of importance to the developer/operator of the system. so how about `sampling.priority`; implicit default value is `0`. OT impls can do what they please with nonzero values; the naive thing would be to treat `sampling.priority > 0` as “please sample this”.

**Comment by yurishkuro** [comment]
Considering this closed by `sampling.priority`

https://github.com/opentracing/opentracing-go/blob/master/ext/tags.go#L25

**Comment by yurishkuro** [comment]
Re-opening to fix typos in the doc and also add constant to Python/Go with the corresponding doc strings.

**Comment by yurishkuro** [comment]
oops, clicking the last check-box auto-closed the issue

**Comment by adriancole** [comment]
ps here's an image of "level" which was discussed at the distributed tracing workshop, particularly by @CodingFabian... similar to what was done here
 
![img_20160202_113635580 1](https://cloud.githubusercontent.com/assets/64215/13193882/d5b638d4-d7bb-11e5-9723-6126cb1af3ab.jpg)

**Comment by beberlei** [comment]
@yurishkuro i think this issue can be closed, its implemented in go and python and is part of the specification on the page, even in examples.
