### ISSUE TITLE
Sample decision propagation query

### ISSUE THREAD

**Issue by drpacman** [opentracing/opentracing.github.io#86]
(re-opened in this repo from issue https://github.com/openzipkin/zipkin/issues/1087)

A bit of background:
My understanding of the sampled approach in Dapper and Zipkin is that a sampling decision is made at the "edge" of the system. It must be propagated to downstreams services in both the positive (we are sampling) and negative (we are not sampling) cases, and must be honoured by the downstream system.
By this I mean the downstream system should not make an independent decision of wether to sample the request.

To accomplish this a header (X-B3-Sampled ) is added to downstream client calls. According to http://zipkin.io/pages/instrumenting.html this value should be a 1 or a 0.

However the original Finagle code appears to use "true" and "false" rather then 1 or 0 (see function on line 349 setClientRequestHeaders):

https://www.codatlas.com/github.com/twitter/finagle/develop/finagle-http/src/main/scala/com/twitter/finagle/http/Codec.scala

Which serialises the value from a Scala Option[Boolean]
https://www.codatlas.com/github.com/twitter/finagle/develop/finagle-core/src/main/scala/com/twitter/finagle/tracing/Id.scala

The Brave implementation appears to handle both:
https://github.com/openzipkin/brave/blob/fd3cdb921964a0d7164c29141fe6aac8099ae4cf/brave-http/src/main/java/com/github/kristofa/brave/http/HttpServerRequestAdapter.java

Questions:
Is my understanding of the importance of honouring sampling decisions at the edge in line with others understanding. 
Secondly, which form for X-B3-Sampled is correct - the arch page or the Finagle code? Am I looking in the wrong place?

**Comment by drpacman** [comment]
From previous issue home, @adriancole answered:

To answer, I think most instrumentation use 0 or 1 for that header, but we
could clarify it as a choice of true/false or 1/0. We need to check that
other tracers accept that,  though, particularly those in the openzipkin
organization) brave and zipkin-tracer (ruby)). Great example of where
interoperability testing  could help

**Comment by drpacman** [comment]
If my statement that the downstream service must honour the sampling decision of the upstream system is correct, it would be useful to clarify the wording in the docs (http://zipkin.io/pages/instrumenting.html). It currently states "Sampled - Lets the downstream service know if it should record trace information for the request.". I think it would be useful to highlight the reasons why honouring sampling decisions are important. I believe these reasons are
(a) Ensure a distributed trace is achievable. If sampling is not consistently honoured then the chances of achieving a complete trace becomes the product of all service sampling choices
(b) Ensure that traces are generated which always start with the origination of the trace, aiding understandability and reducing the risk of cumulative sample rates (e.g. sampling rate of A + sampling rate of B) causing additional traffic to collectors across the estate

**Comment by yurishkuro** [comment]
@drpacman so, a couple of things:

1. the concept of sampling that you describe is known as "pre-trace" or "upfront" sampling. It does require that downstream systems honor the sampling decision made at the edge.  However, that is not the only sampling mechanism that tracing systems may use. Some systems are built to do "post-trace" or "tail" sampling, i.e. after observing the whole trace you decide if it's interesting enough to keep in storage. Because of that, the whole notion of "sampling" is not directly addressed in OpenTracing, leaving it as n implementation detail of the tracing systems.
1. your comments about X-B3-Sampled header and zipkin.io documentation are yet another level down into the implementation world, they are best raised in openzipkin org or https://gitter.im/openzipkin/zipkin

Having said that, pre-trace sampling is by far the most often used technique, so some guidelines like the ones you wrote might be indeed useful somewhere in http://opentracing.io/implementors/

**Comment by drpacman** [comment]
@yurishkuro, thanks for the feedback. I have re-raised this in zipkin documentation (https://github.com/openzipkin/openzipkin.github.io)
